title: "Sn0ox"
name: "Sn0ox"
url: "https://sn0ox.github.io/"
repository: "sn0ox/sn0ox.github.io"
baseurl: ""
staticman:
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "gh-pages"



include:
  - _pages
  - assets
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist

# Build settings
markdown: kramdown
theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"

# Sass/SCSS
sass:
  sass_dir: _sass
 
# settings for author profile
author:
  name   : "Sn0ox"
  avatar : "/assets/images/avatar.png"
  bio    : "Penetration Tester and Security Researcher"


analytics:
  provider: "google"
  google:
    tracking_id: "G-6FW39BECF2"


# pagination for blog page
paginate: 10 # number of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
      toc: true
      toc_label: "Contents"
      toc_sticky: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # posts
  - scope:
      type: posts
    values:
      read_time: true
      share: true
      toc: true
      toc_label: "Contents"
      toc_sticky: true

compress_html:
  clippings: all
  ignore:
    envs: development
